---
- hosts: javaserver
  remote_user: jenkins
  become: yes
  become_method: sudo
  tasks:

   - name: upgrade all packages
     yum:
     name: '*'
     state: latest
   
   - name: Install pip
     yum: name=python-pip state=present
        
   - name: install docker-py
     pip: name=docker-py
        
  
